ERROR - 2022-05-19 20:07:10 --> Error connecting to the database: No connection could be made because the target machine actively refused it
CRITICAL - 2022-05-19 20:07:10 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
#0 C:\xampp\htdocs\i-can\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\i-can\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\i-can\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\i-can\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(156): CodeIgniter\BaseModel->first()
#5 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#6 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Controllers\AuthController.php(88): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#7 C:\xampp\htdocs\i-can\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptLogin()
#8 C:\xampp\htdocs\i-can\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2022-05-19 23:11:07 --> Class name must be a valid object or a string
#0 C:\xampp\htdocs\i-can\system\Config\BaseService.php(248): Myth\Auth\Config\Services::activator(Object(Myth\Auth\Config\Auth), false)
#1 C:\xampp\htdocs\i-can\system\Config\BaseService.php(189): CodeIgniter\Config\BaseService::__callStatic('activator', Array)
#2 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Config\Services.php(86): CodeIgniter\Config\BaseService::getSharedInstance('activator', NULL)
#3 C:\xampp\htdocs\i-can\system\Config\BaseService.php(248): Myth\Auth\Config\Services::activator()
#4 C:\xampp\htdocs\i-can\system\Common.php(929): CodeIgniter\Config\BaseService::__callStatic('activator', Array)
#5 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Controllers\AuthController.php(195): service('activator')
#6 C:\xampp\htdocs\i-can\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptRegister()
#7 C:\xampp\htdocs\i-can\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}
