ERROR - 2022-06-06 04:45:32 --> Error connecting to the database: No connection could be made because the target machine actively refused it
CRITICAL - 2022-06-06 04:45:32 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
#0 C:\xampp\htdocs\i-can\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\i-can\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\i-can\system\Model.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\i-can\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '8')
#4 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Authentication\AuthenticationBase.php(137): CodeIgniter\BaseModel->find('8')
#5 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(70): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#6 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Filters\LoginFilter.php(45): Myth\Auth\Authentication\LocalAuthenticator->check()
#7 C:\xampp\htdocs\i-can\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#8 C:\xampp\htdocs\i-can\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('user/riwayat/us...', 'before')
#9 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
ERROR - 2022-06-06 04:45:36 --> Error connecting to the database: No connection could be made because the target machine actively refused it
CRITICAL - 2022-06-06 04:45:36 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
#0 C:\xampp\htdocs\i-can\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\i-can\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\i-can\system\Model.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\i-can\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '8')
#4 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Authentication\AuthenticationBase.php(137): CodeIgniter\BaseModel->find('8')
#5 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(70): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#6 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Filters\LoginFilter.php(45): Myth\Auth\Authentication\LocalAuthenticator->check()
#7 C:\xampp\htdocs\i-can\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#8 C:\xampp\htdocs\i-can\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('user/riwayat/us...', 'before')
#9 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
ERROR - 2022-06-06 04:45:40 --> Error connecting to the database: No connection could be made because the target machine actively refused it
CRITICAL - 2022-06-06 04:45:40 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
#0 C:\xampp\htdocs\i-can\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\i-can\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\i-can\system\Model.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\i-can\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '8')
#4 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Authentication\AuthenticationBase.php(137): CodeIgniter\BaseModel->find('8')
#5 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(70): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#6 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Filters\LoginFilter.php(45): Myth\Auth\Authentication\LocalAuthenticator->check()
#7 C:\xampp\htdocs\i-can\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#8 C:\xampp\htdocs\i-can\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('user/riwayat/us...', 'before')
#9 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
ERROR - 2022-06-06 04:45:44 --> Error connecting to the database: No connection could be made because the target machine actively refused it
CRITICAL - 2022-06-06 04:45:44 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
#0 C:\xampp\htdocs\i-can\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\i-can\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\i-can\system\Model.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\i-can\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '8')
#4 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Authentication\AuthenticationBase.php(137): CodeIgniter\BaseModel->find('8')
#5 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(70): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#6 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Filters\LoginFilter.php(45): Myth\Auth\Authentication\LocalAuthenticator->check()
#7 C:\xampp\htdocs\i-can\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#8 C:\xampp\htdocs\i-can\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('user/riwayat/us...', 'before')
#9 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
ERROR - 2022-06-06 04:45:49 --> Error connecting to the database: No connection could be made because the target machine actively refused it
CRITICAL - 2022-06-06 04:45:49 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
#0 C:\xampp\htdocs\i-can\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\i-can\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\i-can\system\Model.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\i-can\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '8')
#4 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Authentication\AuthenticationBase.php(137): CodeIgniter\BaseModel->find('8')
#5 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(70): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#6 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Filters\LoginFilter.php(45): Myth\Auth\Authentication\LocalAuthenticator->check()
#7 C:\xampp\htdocs\i-can\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#8 C:\xampp\htdocs\i-can\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('user/riwayat/us...', 'before')
#9 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
ERROR - 2022-06-06 04:45:53 --> Error connecting to the database: No connection could be made because the target machine actively refused it
CRITICAL - 2022-06-06 04:45:53 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
#0 C:\xampp\htdocs\i-can\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\i-can\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\i-can\system\Model.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\i-can\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '8')
#4 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Authentication\AuthenticationBase.php(137): CodeIgniter\BaseModel->find('8')
#5 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(70): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#6 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Filters\LoginFilter.php(45): Myth\Auth\Authentication\LocalAuthenticator->check()
#7 C:\xampp\htdocs\i-can\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#8 C:\xampp\htdocs\i-can\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('user/riwayat/us...', 'before')
#9 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
ERROR - 2022-06-06 04:46:14 --> Error connecting to the database: No connection could be made because the target machine actively refused it
CRITICAL - 2022-06-06 04:46:14 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
#0 C:\xampp\htdocs\i-can\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\i-can\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\i-can\system\Model.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\i-can\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '8')
#4 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Authentication\AuthenticationBase.php(137): CodeIgniter\BaseModel->find('8')
#5 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(70): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#6 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Filters\LoginFilter.php(45): Myth\Auth\Authentication\LocalAuthenticator->check()
#7 C:\xampp\htdocs\i-can\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#8 C:\xampp\htdocs\i-can\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('user/riwayat/', 'before')
#9 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
ERROR - 2022-06-06 04:46:18 --> Error connecting to the database: No connection could be made because the target machine actively refused it
CRITICAL - 2022-06-06 04:46:18 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
#0 C:\xampp\htdocs\i-can\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\i-can\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\i-can\system\Model.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\i-can\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '8')
#4 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Authentication\AuthenticationBase.php(137): CodeIgniter\BaseModel->find('8')
#5 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(70): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#6 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Filters\LoginFilter.php(45): Myth\Auth\Authentication\LocalAuthenticator->check()
#7 C:\xampp\htdocs\i-can\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#8 C:\xampp\htdocs\i-can\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('user/riwayat/', 'before')
#9 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
ERROR - 2022-06-06 04:46:56 --> Error connecting to the database: No connection could be made because the target machine actively refused it
CRITICAL - 2022-06-06 04:46:56 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
#0 C:\xampp\htdocs\i-can\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\i-can\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\i-can\system\Model.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\i-can\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '8')
#4 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Authentication\AuthenticationBase.php(137): CodeIgniter\BaseModel->find('8')
#5 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(70): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#6 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Filters\LoginFilter.php(45): Myth\Auth\Authentication\LocalAuthenticator->check()
#7 C:\xampp\htdocs\i-can\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#8 C:\xampp\htdocs\i-can\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('user/riwayat/', 'before')
#9 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
ERROR - 2022-06-06 04:47:04 --> Error connecting to the database: No connection could be made because the target machine actively refused it
CRITICAL - 2022-06-06 04:47:04 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
#0 C:\xampp\htdocs\i-can\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\i-can\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\i-can\system\Model.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\i-can\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '8')
#4 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Authentication\AuthenticationBase.php(137): CodeIgniter\BaseModel->find('8')
#5 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(70): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#6 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Filters\LoginFilter.php(45): Myth\Auth\Authentication\LocalAuthenticator->check()
#7 C:\xampp\htdocs\i-can\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#8 C:\xampp\htdocs\i-can\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('user/riwayat/', 'before')
#9 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
ERROR - 2022-06-06 04:47:16 --> Error connecting to the database: No connection could be made because the target machine actively refused it
CRITICAL - 2022-06-06 04:47:16 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
#0 C:\xampp\htdocs\i-can\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\i-can\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\i-can\system\Model.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\i-can\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '8')
#4 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Authentication\AuthenticationBase.php(137): CodeIgniter\BaseModel->find('8')
#5 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(70): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#6 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Filters\LoginFilter.php(45): Myth\Auth\Authentication\LocalAuthenticator->check()
#7 C:\xampp\htdocs\i-can\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#8 C:\xampp\htdocs\i-can\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('user/riwayat/', 'before')
#9 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2022-06-06 04:56:45 --> Too few arguments to function App\Controllers\User::riwayat(), 0 passed in C:\xampp\htdocs\i-can\system\CodeIgniter.php on line 832 and exactly 1 expected
#0 C:\xampp\htdocs\i-can\system\CodeIgniter.php(832): App\Controllers\User->riwayat()
#1 C:\xampp\htdocs\i-can\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-06-06 04:58:15 --> Too few arguments to function App\Controllers\User::riwayat(), 0 passed in C:\xampp\htdocs\i-can\system\CodeIgniter.php on line 832 and exactly 1 expected
#0 C:\xampp\htdocs\i-can\system\CodeIgniter.php(832): App\Controllers\User->riwayat()
#1 C:\xampp\htdocs\i-can\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-06-06 04:58:17 --> Too few arguments to function App\Controllers\User::riwayat(), 0 passed in C:\xampp\htdocs\i-can\system\CodeIgniter.php on line 832 and exactly 1 expected
#0 C:\xampp\htdocs\i-can\system\CodeIgniter.php(832): App\Controllers\User->riwayat()
#1 C:\xampp\htdocs\i-can\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-06-06 05:00:53 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\i-can\app\Views\user\riwayat.php(25): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 25)
#1 C:\xampp\htdocs\i-can\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\i-can\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\i-can\system\Common.php(1089): CodeIgniter\View\View->render('user/riwayat', Array, true)
#4 C:\xampp\htdocs\i-can\app\Controllers\User.php(36): view('user/riwayat', Array)
#5 C:\xampp\htdocs\i-can\system\CodeIgniter.php(832): App\Controllers\User->riwayat()
#6 C:\xampp\htdocs\i-can\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-06-06 05:01:39 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\i-can\app\Views\user\riwayat.php(25): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 25)
#1 C:\xampp\htdocs\i-can\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\i-can\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\i-can\system\Common.php(1089): CodeIgniter\View\View->render('user/riwayat', Array, true)
#4 C:\xampp\htdocs\i-can\app\Controllers\User.php(36): view('user/riwayat', Array)
#5 C:\xampp\htdocs\i-can\system\CodeIgniter.php(832): App\Controllers\User->riwayat()
#6 C:\xampp\htdocs\i-can\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-06-06 05:21:51 --> Too few arguments to function App\Controllers\User::detail(), 1 passed in C:\xampp\htdocs\i-can\system\CodeIgniter.php on line 832 and exactly 2 expected
#0 C:\xampp\htdocs\i-can\system\CodeIgniter.php(832): App\Controllers\User->detail('2')
#1 C:\xampp\htdocs\i-can\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-06-06 05:23:20 --> Too few arguments to function App\Controllers\User::detail(), 1 passed in C:\xampp\htdocs\i-can\system\CodeIgniter.php on line 832 and exactly 2 expected
#0 C:\xampp\htdocs\i-can\system\CodeIgniter.php(832): App\Controllers\User->detail('2')
#1 C:\xampp\htdocs\i-can\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-06-06 05:23:21 --> Too few arguments to function App\Controllers\User::detail(), 1 passed in C:\xampp\htdocs\i-can\system\CodeIgniter.php on line 832 and exactly 2 expected
#0 C:\xampp\htdocs\i-can\system\CodeIgniter.php(832): App\Controllers\User->detail('2')
#1 C:\xampp\htdocs\i-can\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-06-06 05:23:29 --> Too few arguments to function App\Controllers\User::detail(), 1 passed in C:\xampp\htdocs\i-can\system\CodeIgniter.php on line 832 and exactly 2 expected
#0 C:\xampp\htdocs\i-can\system\CodeIgniter.php(832): App\Controllers\User->detail('2')
#1 C:\xampp\htdocs\i-can\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-06-06 05:25:25 --> Too few arguments to function App\Controllers\User::detail(), 1 passed in C:\xampp\htdocs\i-can\system\CodeIgniter.php on line 832 and exactly 2 expected
#0 C:\xampp\htdocs\i-can\system\CodeIgniter.php(832): App\Controllers\User->detail('2')
#1 C:\xampp\htdocs\i-can\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
ERROR - 2022-06-06 05:27:03 --> Unknown column 'transaction_id' in 'where clause'
CRITICAL - 2022-06-06 05:27:03 --> Unknown column 'transaction_id' in 'where clause'
#0 C:\xampp\htdocs\i-can\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\i-can\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\i-can\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\i-can\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\i-can\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\i-can\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\i-can\app\Controllers\User.php(47): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\i-can\system\CodeIgniter.php(832): App\Controllers\User->detail('2')
#8 C:\xampp\htdocs\i-can\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#9 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
ERROR - 2022-06-06 05:28:38 --> Unknown column 'transaction_id' in 'where clause'
CRITICAL - 2022-06-06 05:28:38 --> Unknown column 'transaction_id' in 'where clause'
#0 C:\xampp\htdocs\i-can\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\i-can\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\i-can\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\i-can\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\i-can\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\i-can\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\i-can\app\Controllers\User.php(48): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\i-can\system\CodeIgniter.php(832): App\Controllers\User->detail('2')
#8 C:\xampp\htdocs\i-can\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#9 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2022-06-06 05:28:53 --> Undefined variable $bid
#0 C:\xampp\htdocs\i-can\app\Controllers\User.php(58): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 58)
#1 C:\xampp\htdocs\i-can\system\CodeIgniter.php(832): App\Controllers\User->detail('2')
#2 C:\xampp\htdocs\i-can\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
ERROR - 2022-06-06 05:31:21 --> Unknown column 'transaction_id' in 'where clause'
CRITICAL - 2022-06-06 05:31:21 --> Unknown column 'transaction_id' in 'where clause'
#0 C:\xampp\htdocs\i-can\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\i-can\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\i-can\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\i-can\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\i-can\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\i-can\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\i-can\app\Controllers\User.php(48): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\i-can\system\CodeIgniter.php(832): App\Controllers\User->detail('2')
#8 C:\xampp\htdocs\i-can\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#9 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2022-06-06 05:32:01 --> Undefined array key "bid_order_id"
#0 C:\xampp\htdocs\i-can\app\Controllers\User.php(49): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 49)
#1 C:\xampp\htdocs\i-can\system\CodeIgniter.php(832): App\Controllers\User->detail('2')
#2 C:\xampp\htdocs\i-can\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-06-06 06:46:12 --> Undefined variable $user
#0 C:\xampp\htdocs\i-can\app\Views\user\account.php(45): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 45)
#1 C:\xampp\htdocs\i-can\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\i-can\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\i-can\system\Common.php(1089): CodeIgniter\View\View->render('user/account', Array, true)
#4 C:\xampp\htdocs\i-can\app\Controllers\User.php(25): view('user/account', Array)
#5 C:\xampp\htdocs\i-can\system\CodeIgniter.php(832): App\Controllers\User->account()
#6 C:\xampp\htdocs\i-can\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-06-06 08:04:54 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\i-can\app\Controllers\User.php(46): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 46)
#1 C:\xampp\htdocs\i-can\system\CodeIgniter.php(832): App\Controllers\User->detail('3')
#2 C:\xampp\htdocs\i-can\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-06-06 08:25:01 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\i-can\app\Controllers\User.php(46): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 46)
#1 C:\xampp\htdocs\i-can\system\CodeIgniter.php(832): App\Controllers\User->detail('2')
#2 C:\xampp\htdocs\i-can\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-06-06 08:43:05 --> Class name must be a valid object or a string
#0 C:\xampp\htdocs\i-can\system\Config\BaseService.php(248): Myth\Auth\Config\Services::activator(Object(Myth\Auth\Config\Auth), false)
#1 C:\xampp\htdocs\i-can\system\Config\BaseService.php(189): CodeIgniter\Config\BaseService::__callStatic('activator', Array)
#2 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Config\Services.php(86): CodeIgniter\Config\BaseService::getSharedInstance('activator', NULL)
#3 C:\xampp\htdocs\i-can\system\Config\BaseService.php(248): Myth\Auth\Config\Services::activator()
#4 C:\xampp\htdocs\i-can\system\Common.php(929): CodeIgniter\Config\BaseService::__callStatic('activator', Array)
#5 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Controllers\AuthController.php(195): service('activator')
#6 C:\xampp\htdocs\i-can\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptRegister()
#7 C:\xampp\htdocs\i-can\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-06-06 19:42:11 --> Call to undefined function CodeIgniter\locale_set_default()
#0 C:\xampp\htdocs\i-can\system\bootstrap.php(146): CodeIgniter\CodeIgniter->initialize()
#1 C:\xampp\htdocs\i-can\spark(45): require('C:\\xampp\\htdocs...')
#2 {main}
CRITICAL - 2022-06-06 12:45:34 --> Class name must be a valid object or a string
#0 C:\xampp\htdocs\i-can\system\Config\BaseService.php(248): Myth\Auth\Config\Services::activator(Object(Myth\Auth\Config\Auth), false)
#1 C:\xampp\htdocs\i-can\system\Config\BaseService.php(189): CodeIgniter\Config\BaseService::__callStatic('activator', Array)
#2 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Config\Services.php(86): CodeIgniter\Config\BaseService::getSharedInstance('activator', NULL)
#3 C:\xampp\htdocs\i-can\system\Config\BaseService.php(248): Myth\Auth\Config\Services::activator()
#4 C:\xampp\htdocs\i-can\system\Common.php(929): CodeIgniter\Config\BaseService::__callStatic('activator', Array)
#5 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Controllers\AuthController.php(195): service('activator')
#6 C:\xampp\htdocs\i-can\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptRegister()
#7 C:\xampp\htdocs\i-can\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-06-06 12:47:31 --> Class name must be a valid object or a string
#0 C:\xampp\htdocs\i-can\system\Config\BaseService.php(248): Myth\Auth\Config\Services::activator(Object(Myth\Auth\Config\Auth), false)
#1 C:\xampp\htdocs\i-can\system\Config\BaseService.php(189): CodeIgniter\Config\BaseService::__callStatic('activator', Array)
#2 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Config\Services.php(86): CodeIgniter\Config\BaseService::getSharedInstance('activator', NULL)
#3 C:\xampp\htdocs\i-can\system\Config\BaseService.php(248): Myth\Auth\Config\Services::activator()
#4 C:\xampp\htdocs\i-can\system\Common.php(929): CodeIgniter\Config\BaseService::__callStatic('activator', Array)
#5 C:\xampp\htdocs\i-can\vendor\myth\auth\src\Controllers\AuthController.php(195): service('activator')
#6 C:\xampp\htdocs\i-can\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptRegister()
#7 C:\xampp\htdocs\i-can\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}
ERROR - 2022-06-06 23:59:14 --> Unknown column 'bid_id' in 'where clause'
CRITICAL - 2022-06-06 23:59:14 --> Call to a member function getFirstRow() on bool
#0 C:\xampp\htdocs\i-can\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#1 C:\xampp\htdocs\i-can\app\Controllers\User.php(51): CodeIgniter\BaseModel->first()
#2 C:\xampp\htdocs\i-can\system\CodeIgniter.php(832): App\Controllers\User->detail('2')
#3 C:\xampp\htdocs\i-can\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#4 C:\xampp\htdocs\i-can\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\i-can\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\i-can\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#7 {main}
